### ISSUE TITLE
Add Sorting in C++

### ISSUE THREAD

**Issue by SharyDev** [SharyDev/Hacktoberfest-2022#1]

**Comment by Madhvik007** [comment]
Can we use any algorithm?

**Comment by SharyDev** [comment]
> Can we use any algorithm?

Yes

**Comment by Madhvik007** [comment]
I would like to be assigned for this

**Comment by paras3624** [comment]
Hey! Can i contribute to this issue?

**Comment by SharyDev** [comment]
@paras3624 sure.

**Comment by paras3624** [comment]
@SharyDev kindly check my PR.

**Comment by SUSAJJIT** [comment]
assign this to me
