### ISSUE TITLE
Add DSA in C++

### ISSUE THREAD

**Issue by SharyDev** [SharyDev/Hacktoberfest-2022#2]

**Comment by Rkpani05** [comment]
Elaborate it please

**Comment by VAIBHAV0526** [comment]
hey can i contribute basic tree algorithms   like ,lowest common ancestor, diameter of tree,binary lifting and eular tour

**Comment by SharyDev** [comment]
> Elaborate it please

You could add any mechanism that uses DSA concept.

**Comment by SharyDev** [comment]
> hey can i contribute basic tree algorithms like ,lowest common ancestor, diameter of tree,binary lifting and eular tour

Sure if its not their then feel free to contribute.

**Comment by Rkpani05** [comment]
> > Elaborate it please
> 
> You could add any mechanism that uses DSA concept.

Sir i have contriburted some sorts plese check and accept my request
